apiVersion: v1
kind: Service
metadata:
  name: kibana-logging-service
  namespace: elastic-system
  labels:
    k8s-app: kibana-logging
spec:
  selector:
    k8s-app: kibana-logging
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  type: NodePort
