apiVersion: v1
kind: Service
metadata:
  name: rahasak-elasticsearch-es-http
  namespace: elastic-system
spec:
  selector: 
    app: elasticsearch
  type: NodePort  
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 31200